### ISSUE TITLE
Can not run Flem

### ISSUE THREAD

**Issue by BilalReffas** [JustinBeckwith/flem#3]
See the error message below :)

```
error:    TypeError: winston.apply is not a function
    at Builder.builder_1.Builder.on (/usr/local/lib/node_modules/flem/bin/cli.js:21:13)
    at emitTwo (events.js:106:13)
    at Builder.emit (events.js:191:7)
    at OutputManager.log (/usr/local/lib/node_modules/flem/lib/outputManager.js:21:19)
    at OutputManager.info (/usr/local/lib/node_modules/flem/lib/outputManager.js:18:14)
    at prepare.then.generatedFiles (/usr/local/lib/node_modules/flem/lib/builder.js:114:29)
```

**Comment by JustinBeckwith** [comment]
Sorry about that!  This is fixed in the latest release.

**Comment by BilalReffas** [comment]
great thank you :)
